[workspace]
members = ["macros"]

[package]
name = "validex"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = """
Input validating library.
"""
keywords = ["validation"]

[dependencies]
validex-macros = { version = "0.2.0" , path = "macros" }