[package]
name = "validex-macros"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = """
Input validating library.
"""
keywords = ["validation"]

[lib]
proc-macro = true

[dependencies]
quote2 = "0.9"
syn = "2"